/********************************************************************************
** Form generated from reading UI file 'virtualconcierge.ui'
**
** Created by: Qt User Interface Compiler version 5.4.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VIRTUALCONCIERGE_H
#define UI_VIRTUALCONCIERGE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "RenderStates/virtualconciergerenderstate.h"

QT_BEGIN_NAMESPACE

class Ui_VirtualConcierge
{
public:
    VirtualConciergeRenderstate *openGLWidget;
    QWidget *widget_directory;
    QWidget *widget;
    QHBoxLayout *horizontalLayout;
    QPushButton *pushButton_send_mail;
    QLineEdit *lineEdit_email;

    void setupUi(QWidget *VirtualConcierge)
    {
        if (VirtualConcierge->objectName().isEmpty())
            VirtualConcierge->setObjectName(QStringLiteral("VirtualConcierge"));
        VirtualConcierge->resize(480, 800);
        openGLWidget = new VirtualConciergeRenderstate(VirtualConcierge);
        openGLWidget->setObjectName(QStringLiteral("openGLWidget"));
        openGLWidget->setGeometry(QRect(0, 0, 481, 471));
        widget_directory = new QWidget(VirtualConcierge);
        widget_directory->setObjectName(QStringLiteral("widget_directory"));
        widget_directory->setGeometry(QRect(0, 470, 480, 320));
        widget_directory->setStyleSheet(QLatin1String("/* Basic Palette\n"
"border styles: dashed | dot-dash | dot-dot-dash | dotted | double | groove | inset | outset | ridge | solid | none\n"
"*/\n"
"\n"
"/* Set the selection colors for all widgets. */\n"
"QWidget\n"
"{\n"
"	color: #111111;\n"
"	border: 0px solid #737373;\n"
"	background: #727272;\n"
"	selection-color: #cccccc;\n"
"	selection-background-color: #686868;\n"
"	padding: 0px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"QMainWindow\n"
"{\n"
"	background: #727272;\n"
"	padding: 0px;\n"
"	margin: 0px;\n"
"	border: 0px solid #1a1a1a;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal\n"
"{\n"
"    background: #ff0000;\n"
"    max-width: 2px;\n"
"	width: 2px;\n"
"	border-top: 1px solid #393939;\n"
"	border-bottom: 1px solid #959595;\n"
"}\n"
"\n"
"QMainWindow::separator:vertical\n"
"{\n"
"    background: #ff0000;\n"
"    max-height: 2px;\n"
"	height: 2px;\n"
"	border-left: 1px solid #393939;\n"
"	border-right: 1px solid #959595;\n"
"}\n"
"QMainWindow::separator:hover\n"
"{\n"
"    background: #686868;\n"
"}\n"
"\n"
"/"
                        "* Customize check boxes. */\n"
"QCheckBox \n"
"{\n"
"    spacing: 5px;\n"
"   	/*border: 1px solid #242424;*/\n"
"	/*background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #686868);*/\n"
" 	background: transparent;\n"
"	max-width: 200px;\n"
"    max-height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    /*image: url(:/checkbox_checked);*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover\n"
"{\n"
"    /*image: url(:/checkbox_checked_hover);*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed\n"
"{\n"
"  /*  image: url(:/checkbox_checked_pressed);*/\n"
"}\n"
"\n"
"/* Combobox */\n"
"QComboBox \n"
"{\n"
"	border: 1px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"	color: #c8c8c8;\n"
"	border-top-left-radius: 4px; /* same radius as the QComboBox */\n"
"	border-bottom-left-radius: 4px;\n"
"	border-top-right-radius: 4px;\n"
"	b"
                        "order-bottom-right-radius: 4px;\n"
"	padding: 1px 18px 1px 13px;\n"
"	min-width: 6em;\n"
"	max-height: 15px;\n"
"}\n"
"\n"
"/* The popup */\n"
"QComboBox QAbstractItemView {\n"
"	border: 1px solid #303030;\n"
"	background: #212121;\n"
"	selection-background-color: #484848;\n"
"	selection-color: #ffffff;\n"
"	color: #c8c8c8;\n"
"}\n"
"\n"
"QComboBox:editable\n"
"{\n"
"	border: 1px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);	\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable\n"
"{\n"
"	border: 1px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"	\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on\n"
"{\n"
"	border: 1px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"	\n"
"}\n"
"\n"
"QComboBox:on\n"
"{ \n"
"	/* shift the text when th"
                        "e popup opens */\n"
"	padding-top: 3px;\n"
"	padding-left: 4px;\n"
"	border: 1px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"}\n"
"\n"
"/* Drop down button */\n"
"QComboBox::drop-down\n"
"{\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 15px;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"	border: 0px solid #818181;\n"
"	border-top-right-radius: 6px; /* same radius as the QComboBox */\n"
"	border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/arrow_down);\n"
"     width: 11px;\n"
"     height: 6px;\n"
"}\n"
"\n"
"QComboBox::up-arrow\n"
"{\n"
"     image: url(:/arrow_up);\n"
"     width: 11px;\n"
"     height: 6px;\n"
"}\n"
"\n"
"QDockWidget\n"
"{\n"
"    border-top: 1px solid #1a1a1a;\n"
"	border-bottom: 1px solid #1a1a1a;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    background: qlineargradient("
                        "x1:0, y1:0, x2:0, y2:1, stop:0 #4c4c4c, stop:1 #434343);\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"     border: 0px solid #737373;\n"
"     border-radius: 0px;\n"
"     padding: 0px;\n"
"     background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox\n"
" {\n"
"     border: 1px solid #3a3a3a;\n"
"     background: #727272;\n"
"     border-radius: 5px;\n"
"     margin-top: 20px;\n"
" }\n"
"\n"
"QGroupBox::title\n"
"{\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top left;\n"
"     padding: 0px 0px;\n"
"     color: #0b0b0b;\n"
"     background-color: transparent;\n"
"}\n"
"\n"
"/* Header for ... */\n"
"QHeaderView::section\n"
"{\n"
"	color: #cccccc;\n"
"	background: transparent;\n"
"	padding-left: 4px;\n"
"	border-top: 0px solid #393939;\n"
"	border-bottom: 0px solid #959595;\n"
"	min-height: 15px;\n"
"}\n"
"\n"
"/* Text input box */\n"
"QLineEdit\n"
"{\n"
"	color: #c8c8c8;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #808080, stop:1 #8c8c8c);\n"
"    border: 1px solid #4d4d4d;\n"
"	p"
                        "adding: 0 8px;\n"
"	selection-background-color: #222222;\n"
"	selection-color: #f5f5f5;\n"
"	margin-left: 5px;\n"
"	margin-right: 5px;\n"
"	border-radius: 5px;\n"
"	max-height: 14px;\n"
"	height: 14px;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"	margin-left: 5px;\n"
"	margin-right: 5px;\n"
"	background: none;\n"
"	border: 0px;\n"
"}\n"
"\n"
"/* Drop down style */\n"
"QMenu\n"
"{\n"
"	background: #212121;\n"
"	border: 1px solid #303030;\n"
"	color: #eaeaea;\n"
"}\n"
"\n"
"QMenu::separator \n"
"{\n"
"     image: none;\n"
"     border-top: 1px solid #262626;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"	/* sets background of menu item. set this to something non-transparent\n"
"	if you want menu color and menu item color to be different */\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"	/* when user selects item using mouse or keyboard */\n"
"	background: #3e3e3e;\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"    border-top: 1px solid #8b8b8b;\n"
"	border-left: 0px solid #606060;\n"
"	bord"
                        "er-bottom: 1px solid #939393;\n"
"	border-right: 0px solid #303030;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #686868, stop:0.8 #686868, stop:0.9 #474747, stop:1 #000000);\n"
"	min-height: 20px;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"	spacing: 3px; /* spacing between menu bar items */\n"
"	padding: 1px 4px;\n"
"	background: transparent;\n"
"	color: #111111;\n"
"	max-height: 16px;\n"
"}\n"
"\n"
"/* when selected using mouse or keyboard */\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #464646);\n"
"	color: #ffffff;\n"
"	border-radius: 5px;\n"
"	border:	1px solid #222222;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #464646);\n"
"	color: #ffffff;\n"
"	border-radius: 5px;\n"
"	border:	1px solid #222222;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #0b0b0b;\n"
"    border: 1px solid #353535;\n"
"	background: QLinearGradient( x1: 0, y1: 0, x"
                        "2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"	border-radius: 10px;\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"}\n"
"\n"
"/* all types of push button */\n"
"QPushButton:hover\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #464646);\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #464646);\n"
"	color: #e5e5e5;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #464646);\n"
"	color: #e5e5e5;\n"
"}\n"
"\n"
"\n"
"/* Customize radio buttons. */\n"
"QRadioButton \n"
"{\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator \n"
"{\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked\n"
"{\n"
"    image: url(:/radiobutton_unchecked);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover \n"
"{\n"
"    image: url(:/radio"
                        "button_unchecked_hover);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:pressed \n"
"{\n"
"    image: url(:/radiobutton_unchecked_pressed);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    image: url(:/radiobutton_checked);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover \n"
"{\n"
"    image: url(:/radiobutton_checked_hover);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed \n"
"{\n"
"    image: url(:/radiobutton_checked_pressed);\n"
"}\n"
"\n"
"/* Customize arrows. \n"
"*::down-arrow, *::menu-indicator {\n"
"    image: url(:/arrow_down);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"*::down-arrow:disabled, *::down-arrow:off {\n"
"   image: url(:/down_arrow_disabled.png);\n"
"}\n"
"\n"
"*::up-arrow {\n"
"    image: url(:/arrow_up);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"*::up-arrow:disabled, *::up-arrow:off {\n"
"   image: url(:/up_arrow_disabled.png);\n"
"}\n"
"\n"
"*/\n"
"\n"
"QScrollBar QAbstractScrollArea\n"
"{\n"
"	background: transparent;\n"
"}\n"
"\n"
""
                        "QScrollBar:horizontal\n"
"{\n"
"	max-height: 12px;\n"
"	min-height: 12px;\n"
"	margin: 0px 22px 0px 22px;\n"
"    border: 0px solid #474747;\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"	border: 1px solid #383838;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #969696, stop:1 #7b7b7b);\n"
"	border-radius: 3px;\n"
"	min-height: 8px;\n"
"	max-height: 8px;\n"
"	height: 8px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"	border: 0px solid #1e1e1e;\n"
"    background-color: transparent;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"	border: 0px solid #1e1e1e;\n"
"    background-color: transparent;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"	background-color: transparent;\n"
"    width: 0px;\n"
"    height: 0px;\n"
""
                        "}\n"
"  \n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"	background-color: transparent;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    border: 0px solid #1e1e1e;\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    max-width: 12px;\n"
"	min-width: 12px;\n"
"	margin: 22px 0px 22px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"	border: 1px solid #383838;\n"
"	background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #969696, stop:1 #7b7b7b);\n"
"	border-radius: 3px;\n"
"	min-width: 8px;\n"
"	max-width: 8px;\n"
"	min-height: 20px;\n"
"	max-height: 20px;\n"
"	width: 8px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"	border: 0px solid #1e1e1e;\n"
"	background-color: transparent;\n"
"	height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vert"
                        "ical\n"
"{\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"	border: 0px solid #1e1e1e;\n"
"	background-color: transparent;\n"
"	height: 0px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"	background-color: transparent;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"  \n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"	background-color: transparent;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"QSlider\n"
"{\n"
"	background-color: #808080;\n"
"}\n"
"\n"
"QSlider::groove:vertical\n"
"{\n"
"	background-color: transperant;\n"
"	position: absolute; \n"
"	left: 4px; right: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical\n"
"{\n"
"     height: 10px;\n"
"     background: #ff7603;\n"
"     border: 1px solid #62340e;\n"
"     margin: 0 -4px; /* expand outside the groove */\n"
"}\n"
"\n"
"QSlider::add-page:vertical\n"
"{\n"
"     background: #222222;\n"
"}\n"
"\n"
""
                        "QSlider::sub-page:vertical\n"
"{\n"
"     background: #222222;\n"
"}\n"
"\n"
"QSpinBox \n"
"{\n"
"    padding-right: 15px; /* make room for the arrows */\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #808080, stop:1 #8c8c8c);\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"   	border-top-left-radius: 3px; /* same radius as the QComboBox */\n"
"	border-bottom-left-radius: 3px;\n"
"}\n"
" \n"
"QSpinBox::up-button\n"
"{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    width: 16px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #a6a6a6, stop:1 #979797);\n"
"    border: 1px solid #323232;\n"
"	border-bottom-width: 0;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QSpinBox::up-arrow\n"
"{\n"
"     image: url(:/arrow_u"
                        "p);\n"
"     width: 11px;\n"
"     height: 6px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled, QSpinBox::up-arrow:off\n"
"{ /* off state when value is max */\n"
"    image: url(:/arrow_up);\n"
"}\n"
"\n"
"QSpinBox::down-button\n"
"{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"    width: 16px;\n"
"	border-top: 0px solid #323232;\n"
"	border-left: 1px solid #323232;\n"
"	border-bottom: 1px solid #323232;\n"
"	border-right: 1px solid #323232;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #979797, stop:1 #8a8a8a);\n"
"    border-top-width: 0;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QSpinBox::down-arrow\n"
"{\n"
"     image: url(:/arrow_down);\n"
"     width: 11px;\n"
"     height: 6px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled,\n"
"QSpinBox::down-arrow:off \n"
"{ /* off state when value in min */\n"
""
                        "    image: url(:/arrow_down);\n"
"}\n"
"\n"
"QSplitter::handle \n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal\n"
"{\n"
" 	background: transparent;\n"
" 	min-width: 2px;\n"
"	max-width: 2px;\n"
"	width: 2px;\n"
"	border-left: 1px solid #393939;\n"
"	border-right: 1px solid #959595;\n"
"	padding: 0px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical\n"
"{\n"
"   	background: transparent;\n"
"   	max-height: 2px;\n"
"	min-height: 2px;\n"
"	height: 2px;\n"
"	border-top: 1px solid #393939;\n"
"	border-bottom: 1px solid #959595;\n"
"	padding: 0px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"QStatusBar\n"
"{\n"
"   	border: 0px solid #262626;\n"
"	background: #686868;\n"
"}\n"
"\n"
"/* Table View */\n"
"QTableView\n"
"{\n"
"	background: #727272;\n"
"	selection-background-color: #787878;\n"
"	selection-color: #f5f5f5;\n"
"	padding-left: 5px;\n"
"	padding-right: 5px;\n"
"	color: #000000;\n"
"	margin: 5px;\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"	margin-top: 1px;\n"
"	border: 0px solid #4"
                        "34343;\n"
"	border-radius: 0px;\n"
"	padding: 0px;\n"
"	background: #727272;\n"
"	paint-alternating-row-colors-for-empty-area: 1;\n"
"	show-decoration-selected: 1;\n"
"	alternate-background-color: #727272;\n"
"}\n"
"\n"
"QTreeView::item \n"
"{\n"
"	color: #cccccc;\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"	color: #e5e5e5;\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"	color: #ffffff;\n"
"	background: #686868;\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"	color: #f5f5f5;\n"
"	background: #686868;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"	color: #f5f5f5;\n"
"	background: #686868;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item \n"
"{\n"
"     border-image: url(:/vline) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item \n"
"{\n"
"     border-image: url(:/branch-more) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item\n"
"{\n"
"     border-image: url(:/branch-end) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has"
                        "-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"         image: url(:/branch-closed);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"         border-image: none;\n"
"         image: url(:/branch-open);\n"
"}\n"
"\n"
"/* The tab widget frame */\n"
"QTabWidget::pane\n"
"{\n"
"    border: 1px solid #353535;\n"
"	margin: 0px;\n"
"	padding: 0px;\n"
"	\n"
"}\n"
"\n"
"QTabWidget::tab-bar\n"
"{\n"
"	background: #323232;\n"
"	border: 1px solid #1e1e1e;\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. */\n"
"QTabBar::tab\n"
"{\n"
"	border: 1px solid #353535;\n"
"	border-bottom: 0px solid #242424;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #535353, stop:1 #373737);\n"
"	color: #aaaaaa;\n"
"	padding: 3px;\n"
"	border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"	margin-top: 1px;\n"
"	margin-bottom: 0px;\n"
"	margin-left: 5px;\n"
"}\n"
"\n"
"QTa"
                        "bBar::tab:hover\n"
"{\n"
"	color: #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #a6a6a6, stop:1 #8a8a8a);\n"
"	color: #010101\n"
"}\n"
"\n"
"/* Style for main toolbar */\n"
"QToolBar\n"
"{\n"
"    border: 0px solid #8b8b8b;\n"
"	background-color: transparent;\n"
"	spacing: 2px; /* spacing between items in the tool bar */\n"
"	margin-left: 3px;\n"
"	color: #e5e5e5;\n"
"	max-height: 22px;\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     image: none;\n"
"     background-color: transparent;\n"
"}\n"
" \n"
"QToolBar::separator \n"
"{\n"
"     width: 5px;\n"
"     border: 0px;\n"
"     background-color: transparent;\n"
"}\n"
"\n"
"/* All types of tool button */\n"
"QToolButton\n"
"{\n"
"	border: 1px solid #353535;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #a6a6a6, stop:1 #8a8a8a);\n"
"	color: #e5e5e5;\n"
"	border-radius: 5px;\n"
"	max-height: 18px;\n"
"	min-width: 18px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]\n"
"{\n"
"	/* "
                        "only for MenuButtonPopup */\n"
"	padding-right: 20px; /* make way for the popup button */\n"
"	/* max-width: 32px; */\n"
"}\n"
"\n"
"QToolButton::menu-button\n"
"{\n"
"     /* 16px width + 4px for border = 20px allocated above */\n"
"	border-top: 1px solid #323232;\n"
"	border-left: 1px solid #222222;\n"
"	border-bottom: 1px solid #323232;\n"
"	border-right: 1px solid #323232;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #a6a6a6, stop:1 #8a8a8a);\n"
"	color: #111111;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #e5e5e5, stop:0.2 #a6a6a6, stop:0.8 #8a8a8a, stop:1 #4a4a4a);\n"
"	color: #c8c8c8;\n"
"}\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #e5e5e5, stop:0.2 #a6a6a6, stop:0.8 #8a8a8a, stop:1 #4a4a4a);\n"
"	color: #c8c8c8;\n"
"}\n"
"\n"
"QToolTip\n"
"{\n"
"	border: 1px solid #111111;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #363636, stop:0.2 #e5e5e5, stop:0."
                        "8 #ffffff, stop:1 #262626);\n"
"	padding: 3px;\n"
"	border-radius: 0px;\n"
"	opacity: 150;\n"
"	color: #000000;\n"
"}\n"
"\n"
"QDoubleSpinBox \n"
"{\n"
"    padding-right: 15px; /* make room for the arrows */\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #808080, stop:1 #8c8c8c);\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"   	border-top-left-radius: 3px; /* same radius as the QComboBox */\n"
"	border-bottom-left-radius: 3px;\n"
"}\n"
" \n"
"QDoubleSpinBox::up-button\n"
"{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    width: 16px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #a6a6a6, stop:1 #979797);\n"
"    border: 1px solid #323232;\n"
"	border-bottom-width: 0;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:hover\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:pressed\n"
"{\n"
"	background: #3e3e"
                        "3e;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow\n"
"{\n"
"    /* image: url(:/arrow_up);*/\n"
"     width: 11px;\n"
"     height: 6px;\n"
"}\n"
"\n"
"/*QDoubleSpinBox::up-arrow:disabled, QDoubleSpinBox::up-arrow:off\n"
"{  off state when value is max \n"
"    image: url(:/arrow_up);\n"
"}*/\n"
"\n"
"QDoubleSpinBox::down-button\n"
"{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"    width: 16px;\n"
"	border-top: 0px solid #323232;\n"
"	border-left: 1px solid #323232;\n"
"	border-bottom: 1px solid #323232;\n"
"	border-right: 1px solid #323232;\n"
"	background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #979797, stop:1 #8a8a8a);\n"
"    border-top-width: 0;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:hover\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed\n"
"{\n"
"	background: #3e3e3e;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow\n"
"{\n"
"     image: url(:/arrow_down);\n"
"     width: 11px;\n"
"     height: 6p"
                        "x;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow:disabled,\n"
"QDoubleSpinBox::down-arrow:off \n"
"{ /* off state when value in min */\n"
"    image: url(:/arrow_down);\n"
"}\n"
""));
        widget = new QWidget(widget_directory);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(290, 10, 181, 21));
        horizontalLayout = new QHBoxLayout(widget);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        pushButton_send_mail = new QPushButton(widget);
        pushButton_send_mail->setObjectName(QStringLiteral("pushButton_send_mail"));

        horizontalLayout->addWidget(pushButton_send_mail);

        lineEdit_email = new QLineEdit(widget);
        lineEdit_email->setObjectName(QStringLiteral("lineEdit_email"));

        horizontalLayout->addWidget(lineEdit_email);


        retranslateUi(VirtualConcierge);

        QMetaObject::connectSlotsByName(VirtualConcierge);
    } // setupUi

    void retranslateUi(QWidget *VirtualConcierge)
    {
        VirtualConcierge->setWindowTitle(QApplication::translate("VirtualConcierge", "Virtual Concierge", 0));
        pushButton_send_mail->setText(QApplication::translate("VirtualConcierge", "Mail", 0));
    } // retranslateUi

};

namespace Ui {
    class VirtualConcierge: public Ui_VirtualConcierge {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VIRTUALCONCIERGE_H
