#include "premises_exporter.h"
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QDebug>
PremisesExporter::PremisesExporter(){

}

void PremisesExporter::export_environment(QVector<VisualObject *>,QString){
//    if(!QDir().mkdir("VirtualConcierge"))
//    qDebug()<<"Directory already exists";

//    QFile file("VirtualConcierge/environment.env");
//        file.open(QIODevice::WriteOnly | QIODevice::Text);
//        QTextStream out(&file);
//        for(int l =0;l<10;l++)

//        out << "This file is generated by Qt\n";

//        // optional, as QFile destructor will already do it:
//        file.close();
}

void PremisesExporter::export_nodes(QVector<Node *> nodes,QString name){
if(QDir().mkdir("VirtualConcierge"))
    qDebug()<<"Success in Creating Directory 'VirtualConcierge'";

if(!QDir().cd("VirtualConcierge"))
    qDebug()<<"Directory 'VirtualConcierge' does not exists";

QFile file("VirtualConcierge/"+name);
    file.open(QIODevice::WriteOnly | QIODevice::Text);
    QTextStream out(&file);

    // write the nodes
    for(int l = 0;l < nodes.count();l++){
        out <<"n,"<< l <<","
            << nodes.value(l)->Position().x()<<","
            << nodes.value(l)->Position().y()<<","
            << nodes.value(l)->Position().z()<<","
            << nodes.value(l)->getName()<<"\n";
    }
    // write the links to each node
    for(int k= 0;k < nodes.count();k++){
        for(int j = 0; j<nodes.value(k)->countConnected();j++)
        out <<"j,"<< k<<","<<nodes.value(k)->getConnectedIndex(j)<<"\n";
    }

    // optional, as QFile destructor will already do it:
    file.close();
}
